version: '3.8'

services:
  redis:
    image: 'bitnami/redis:6.2.6'
    environment:
      - REDIS_PORT_NUMBER=6379
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      # TODO specify persistent storage instead of docker volume to allow backup-restore
      - redis-data:/bitnami/redis/data

  activemq:
    image: 'rmohr/activemq:5.15.9'
    ports:
      - '61616:61616'
      - '8161:8161'
    volumes:
      - activemq-conf:/opt/activemq/conf
      - activemq-data:/opt/activemq/data

volumes:
  redis-data:
  activemq-conf:
  activemq-data:
